set(TEPHRA_LLVM_BIN $ENV{LLVM_ROOT}/bin)

if (CMAKE_HOST_WIN32)
   set(CMAKE_C_COMPILER ${TEPHRA_LLVM_BIN}/clang-cl.exe CACHE FILEPATH "")
   set(CMAKE_CXX_COMPILER ${TEPHRA_LLVM_BIN}/clang-cl.exe CACHE FILEPATH "")
   set(CMAKE_RC_COMPILER ${TEPHRA_LLVM_BIN}/llvm-rc.exe CACHE FILEPATH "")
else ()
   set(CMAKE_C_COMPILER ${TEPHRA_LLVM_BIN}/clang CACHE FILEPATH "")
   set(CMAKE_CXX_COMPILER ${TEPHRA_LLVM_BIN}/clang++ CACHE FILEPATH "")
endif ()

unset(TEPHRA_LLVM_BIN)